# Generated by Django 5.0.7 on 2024-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_joined_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Lucifer1147', max_length=25, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
